config {
    type: "table",
    name: "dim_date",
    uniqueKey: ["date_id"],
    description: "Date dimension for time-based analysis. Includes year, quarter, month, weekday, etc."
}

  -- Generate dim_date table with 20 years of data
WITH
  min_date AS (
  SELECT
    MIN(pickup_datetime) AS min_ts
  FROM
    ${ref('l1_clean_trips')} ),
  date_range AS (
    SELECT *
    FROM bigfunctions.us.generate_dates(
      (SELECT CAST(min_ts AS DATE) FROM min_date),
      DATE_ADD(CURRENT_DATE(), INTERVAL 1 YEAR)
    )
  )
SELECT
  *,
  CAST(FORMAT_DATE('%Y%m%d', date) AS INT64) AS date_id,
  EXTRACT(YEAR
  FROM
    date) AS year,
  FORMAT_DATE('%B', date) AS month_name,
  FORMAT_DATE('%b', date) AS month_short,
  bigfunctions.us.is_public_holiday(CAST(date AS DATE),
    "US") AS is_holiday,
  CURRENT_DATE() = date AS is_today,
  CURRENT_DATE() >= date AS is_past,
  CURRENT_DATE() < date AS is_future
FROM
  date_range
