config {
    type: "table",
    schema: "taxi_marts",
    name: "daily_rides",
}

js {
    const {
        NO_DATA,
    } = require("/includes/constants.js");
}

WITH
  calendar AS (
  SELECT
    dim_date.date,
    dim_date.date_id,
    dim_date.year,
    dim_date.month_name,
    dim_date.day_of_week,
    dim_date.is_holiday,
  FROM
    ${ref('dim_date')} dim_date ),
  agg_rides AS (
  SELECT
    pickup_date_id AS date_id,
    vendor_id,
    COALESCE(COUNT(pickup_date_id),0) AS rides,
    COALESCE(SUM(total_amount),0) AS total_amount,
    COALESCE(SUM(passenger_count),0) AS passenger_count,
    SUM(
    IF
      (isNonFraudRide, 0, 1)) AS fraud_rides
  FROM
    ${ref("kimball_dwh_taxi", "fact_trips")}
  GROUP BY
    1,
    2 )
SELECT
  calendar.* EXCEPT(date_id),
  COALESCE(dim_vendor.vendor_name, '${NO_DATA}') AS vendor_name,
  agg_rides.* EXCEPT(vendor_id, date_id)
FROM
  calendar
LEFT JOIN
  agg_rides agg_rides
USING
  (date_id)
LEFT JOIN
  ${ref('dim_vendor')} dim_vendor
USING
  (vendor_id)
ORDER BY
  rides DESC